# Basic configuration file for Syzygy
# This file is in YAML format, see http://www.yaml.org/start.html for more information
logs: "/tmp/syzygy.log"
processes:
    process1:
        command: "echo hello world"
        cwd: "/tmp"
        env:
          - "FOO=bar"
        stop_signal: "SIGINT"
        restart: never
    process2:
        command: "ls -alh"
        restart: never
    sleepy:
        command: "sleep 3"
        restart: unless-stopped
